version: '3'
networks:
  internal_network:
    name: ${INTERNAL_NETWORK_NAME}
    external:
      name: ${EXTERNAL_NETWORK_NAME}
volumes:
  mariadb-data:
  minio-data-1:

services:
  music-app-backend:
    build: ./_docker/backend/${ENVIRONMENT}
    hostname: local-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - ${EXPOSED_BACKEND_PORT}:${INTERNAL_BACKEND_PORT}
    networks:
      - internal_network
    env_file:
      - ./backend/.env
  music-app-db:
    build: ./_docker/db/${ENVIRONMENT}
    hostname: local-db
    volumes:
      - 'mariadb-data:/var/lib/mysql'
    ports:
      - ${EXPOSED_DB_PORT}:${INTERNAL_DB_PORT}
    networks:
      - internal_network
    env_file:
      - ./db/.env
  music-app-minio:
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    command:  minio server /mnt/data1 --console-address ":9001"
    expose:
      - ${INTERNAL_MINIO_S3_PORT}
      - ${INTERNAL_MINIO_CONSOLE_PORT}
    ports:
      - ${EXPOSED_MINIO_S3_PORT}:${INTERNAL_MINIO_S3_PORT}
      - ${EXPOSED_MINIO_CONSOLE_PORT}:${INTERNAL_MINIO_CONSOLE_PORT}
    env_file:
      - ./minio/.env
    volumes:
      - minio-data-1:/data1
    restart: always